### ISSUE TITLE
Change the latin text from homepage guest

### ISSUE THREAD

**Issue by corradodiba** [corradodiba/scm-nodets-backend#33]
https://github.com/corradodiba/stevejobs-class-managing/blob/develop/front-end/src/app/templates/guest/guest-homepage/guest-homepage.component.html

**Comment by manuelcarusoomnia** [comment]
Ok

Sent from my Huawei Mobile

-------- Original Message --------
Subject: Re: [corradodiba/stevejobs-class-managing] Change the latin text from homepage guest (#33)
From: Corrado Dibattista
To: corradodiba/stevejobs-class-managing
CC: Manuel Caruso ,Assign


Assigned #33<https://github.com/corradodiba/stevejobs-class-managing/issues/33> to @Nobodyofsora<https://github.com/Nobodyofsora>.

**Comment by corradodiba** [comment]
solved by @fabriziocannizzaro
