### ISSUE TITLE
Not authentication promise rejection

### ISSUE THREAD

**Issue by corradodiba** [corradodiba/scm-nodets-backend#40]
When a route is called, but user is not authenticated, the promise go to rejection. Fix this problem @Nobodyofsora 

This problem causes a server crash:
`(node:61211) UnhandledPromiseRejectionWarning: Not authenticated!
(node:61211) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61211) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by corradodiba** [comment]
even when trying to authenticate with incorrect credentials

**Comment by manuelcarusoomnia** [comment]
I tried every route and the ones with isAuth are giving out this json: {"message": "You are not authenticated!" and no errors, server-side
Is this not intended?

**Comment by corradodiba** [comment]
Quando vengono inserite delle credenziali sbagliate sulla route `auth/login` il server va in crash, ed è questo il problema principale. Poi potrebbero esserci dei casi isolati sulle altre route, per questo bisogna controllarle tutte. @Nobodyofsora
